# Generated by Django 3.0.5 on 2020-04-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(null=True, to='question_and_answer.Tags'),
        ),
    ]
