# Generated by Django 3.0.5 on 2020-04-22 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_and_answer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='votes_down',
            field=models.ManyToManyField(related_name='user_votes_answer_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='votes_up',
            field=models.ManyToManyField(related_name='user_votes_answer_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='votes_down',
            field=models.ManyToManyField(related_name='user_votes_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='votes_up',
            field=models.ManyToManyField(related_name='user_votes_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
