# Generated by Django 3.0.5 on 2020-04-21 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_and_answer', '0002_auto_20200421_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_voices',
            field=models.ManyToManyField(related_name='user_voices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='question_and_answer.Tags'),
        ),
    ]
