# Generated by Django 3.0.5 on 2020-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0003_auto_20200423_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
