# Generated by Django 3.0.5 on 2020-04-21 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_and_answer', '0003_auto_20200421_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_voices',
        ),
        migrations.AddField(
            model_name='question',
            name='user_votes',
            field=models.ManyToManyField(related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
